// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wcsvrrselgxthldvnwgd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indjc3ZycnNlbGd4dGhsZHZud2dkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1MDcwMDAsImV4cCI6MjA1MzA4MzAwMH0.R-lLlELnGoDPttNnIe5HOFfCkacduVrkOkjUFfqF0X8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);