// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajphbyxiyvbjqfxvakia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqcGhieXhpeXZianFmeHZha2lhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY1NDk3NzYsImV4cCI6MjA1MjEyNTc3Nn0.hcZtetEOonI78_TULwzTmjQeD9Np8nHPGQhE_O6du94";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);